---
- name: Download proxmox-ve-release-6.x.gpg
  get_url:
    url:  http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg
    dest: /etc/apt/trusted.gpg.d/proxmox-ve-release-6.x.gpg
    mode: '0444'

- name: Add the Proxmox VE repository
  apt_repository:
    repo: deb http://download.proxmox.com/debian/pve buster pve-no-subscription
    state: present

- name: Remove specified repository from sources list
  apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/pve buster pve-enterprise
    state: absent

- name: Update repositories cache and full-upgrade
  apt:
    update_cache: 'yes'
    upgrade: 'full'

- name: Install ProxmoxVE
  apt:
    name:
      - proxmox-ve
      - postfix
      - open-iscsi
      - ifupdown2
    state: present

- name: Remove the os-prober package
  apt:
    name:
      - os-prober
      - linux-image-amd64
      - 'linux-image-4.19*'
    state: absent
